### PR TITLE
Response to Reviewers

### LINKED ISSUE #1: Review for 2015 Brainhack Proceedings
I've carefully read the PDF summarizing the project, and I think it looks good. My main (minor) suggestion would be to explicitly point to the GitHub repos in the text somewhere early on. Currently the URLs can be found only at the end. The clickable links in the PDF will direct one to the repos, but it's not clear that the published version will allow this. A comment early on to the effect that the code can be found on GitHub might be helpful.

You could also perhaps mention somewhere in the text that there are much more extensive docs at readthedocs and on GitHub, just to make it clear that this is only a high-level overview of the tools.

Both of these are pretty trivial suggestions, so consider them completely optional.

### LINKED ISSUE #2: Review
I have no major issues. A couple of minor points:
- The intro explains that NIDM describes workflows, observations, etc. Perhaps, referring to a quick example or two might make the abstract more ingestible. I find that if people can quickly relate to the problem, then they are more likely to keep reading. In my opinion, there are many details in the intro that are fairly abstract to a more naive user. Given that the goal of this initiative is involve the entire community, it might be better to make a shorter introduction, and push some of the details, like the SPARQL maybe the JSON stuff to the next section. Short and sweet. 
-  A schematic might aid in the understanding of this tool.
- The first sentence of the conclusion is difficult to ingest. Perhaps rewording it might make for a better emphasis regarding the value of using NIDM.

### PR DESCRIPTION
**Pull request by vsoch**
Thanks @tyarkoni for your prompt feedback on the manuscript. To fix #1 , I've added a mention of the availability of code in Github, along with links to the repos and readthedocs early in the document.

> >  These tools are publicly available on Github (RRID:SCR_002630) at https://github.com/incf-nidash/nidm-api and https://github.com/incf-nidash/nidm-queries for the API and queries, respectfully, along with complete documentation at https://nidm-api.readthedocs.org.

The comments from @samirdas were very helpful! To fix #2, I've adjusted the introduction to include an example, and moved details of the data structures to the next section.

> > For example, a researcher sharing a statistical brain map could include with the brain map a data structure, "NIDM Results,"' that contains complete information about the parameters used to generate the result, significant coordinate points in the brain map paired with test criteria, along with other meta-data exported from the software that generated it. This additional information cannot be represented in the brain map itself, and provides a complete description of the result that can be compared to other results, or used to reproduce it. 

I have added a schematic to aid in the understanding of this tool:

nidm api figure 1 - new page 1

And I've adjusted the first sentence of the conclusion to be less confusing:

> > By providing tools to integrate the NIDM standard into modern web technology, NIDM can be more easily deployed into applications to empower neuroimaging researchers to explore and synthesize results, workflows, and experiments.

I've also fixed other bugs, including references to the repo `nidm-queries` that needs to be `nidm-query,` adding a link to the viewer, and a reference to nidm-results in the Figure 2 that should be "NIDM Results"

The [full PDF is available for review](https://github.com/vsoch/brainhack-nidm-report/blob/master/neuroimaging-data-model.pdf), and bringing @nicholsn into this discussion as well!

### CODE REVIEW

**Comment by nicholsn** [comment]
@vsoch, thanks for the detailed response to the reviewers' comments!

@samirdas and @tyarkoni, do you have any additional comments you would like us to address? If not, let us know and we will merge these changes, close your issues, and submit the final version.

**Comment by tyarkoni** [comment]
Looks good to me!

**Comment by vsoch** [comment]
Thanks @tyarkoni! I think @margulies or @ccraddock will have to do the merge, when @samirdas confirms things look good :)

**Comment by ccraddock** [comment]
Hey Vanessa,

I merged your pull request and added you as an admin on the repo.  Please
check it out and make sure there werent' any problems.

Cheers
-cc

On Tue, Mar 22, 2016 at 7:05 PM, Vanessa Sochat notifications@github.com
wrote:

> Thanks @tyarkoni https://github.com/tyarkoni! I think @margulies
> https://github.com/margulies or @ccraddock
> https://github.com/ccraddock will have to do the merge, when @samirdas
> https://github.com/samirdas confirms things look good :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Brainhack-Proceedings-2015/Sochat-AMX-NIDM/pull/3#issuecomment-200071898

## 

Director of Imaging, Center for the Developing Brain, Child Mind Institute
http://childmind.org
Director, Computational NeuroImaging Lab
http://computational-neuroimaging-lab.org/, Nathan S. Kline Institute for
Psychiatric Research http://www.rfmh.org/nki/
Co-Founder, The Neuro Bureau http://neurobureau.org
Impact Story https://impactstory.org/CameronCraddock
Google Scholar Citations
http://scholar.google.com/citations?user=lZ9hwSsAAAAJ&hl=en
GitHub https://github.com/ccraddock

Share that Brain @ the International Neuroimaging Datasharing Initiative
http://fcon_1000.projects.nitrc.org/!
The GigaScience Brainhack Thematic Series
http://brainhack.org/brainhack-thematic-series-call-for-papers/ is open
for your submission.
Submit a paper to the Neuroimage Special Issue on Brain Segmentation and
Parcellation
http://www.journals.elsevier.com/neuroimage/call-for-papers/brain-segmentation-and-parcellation/
!

Join me at upcoming Brainhack http://brainhack.org Events:
2016.06.26 - 2016.06.30 OHBM Hackathon
http://brainhack.org/ohbm-hackathon-2016/, Lausanne, Switzerland
2016.09.18 - 2016.09.20 Brainhack Vienna http://restingstate.net, Vienna,
Austria

**Comment by vsoch** [comment]
It looks good from my end - the merge updated the current repo to have the paper, pdf and tex and updated images that reflect the current changes to the paper and final draft. @nicholsn can have a final look, and I want to make sure that @samirdas is also ok with the changes, since we have not yet heard from him. If additional edits are needed, I can now manage merging. Thanks @ccraddock!

**Comment by nicholsn** [comment]
:+1:

**Pull request merged**
